title: jsConvert

baseurl: /js-convert-case

urls:
  - url: /
    text: Playground
  - url: /quickstart
    text: Quickstart
  - url: /api
    text: API
  - url: /examples
    text: Examples

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

sass:
  style: compressed

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
